# Generated by Django 5.2 on 2026-07-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_workexperience_alter_project_id_workexperienceimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='start_date',
        ),
    ]
